- name: Install need packages in mac
  community.general.homebrew:
    name: git,stow,neovim,tmux,fzf,gdu,zsh
    state: latest
  tags:
    - mac
- name: Install packages in arch
  community.general.pacman:
    name:
      - git
      - stow
      - neovim
      - tmux
      - fzf
      - gdu
      - zsh
      - ubuntu
    state: latest
  tags:
    - arch
- name: Install packages in debian or ubuntu
  apt:
    name:
      - git
      - stow
      - neovim
      - tmux
      - fzf
      - gdu
      - zsh
    state: latest
    update_cache: yes
  tags:
    - ubuntu
# - name: Clone dotfiles repo
#   ansible.builtin.git:
#     repo: https://github.com/aritraghorai/newdotfiles
#     dest: "{{ lookup('env', 'HOME') }}/dotfiles"
#     version: master
#   tags:
#     - mac
#     - arch
#     - ubuntu
